### PR TITLE
Create CI.yml

### PR DESCRIPTION
**Pull request by ahsanaman92**
PR to create github workflows and build/push nuget package

### CODE REVIEW

**Comment by Numpsy** [comment]
Do we want the builds here or in https://github.com/BoldonJames/JpegXmpWritePluginMDE? (or maybe do something over there after getting everything working?)

**Comment by ahsanaman92** [comment]
> Do we want the builds here or in https://github.com/BoldonJames/JpegXmpWritePluginMDE? (or maybe do something over there after getting everything working?)

I was thinking of getting everything working here and then align BJ repo with it after. Currently working on creating a nuget package via the workflow and then pushing it. This PR requires a little more work. Also, if MDE author is going to do a RC2, maybe align with that here before moving things over?

**Comment by ahsanaman92** [comment]
@Numpsy It is ready for your review now

**Review by Numpsy — APPROVED** [review]

**Comment by Numpsy** [comment]
> Also, if MDE author is going to do a RC2

RC2 appears to be out now

**Pull request merged**
